- hosts: debian1
  become: true
  tasks:
    - name: Entraine un changement
      copy:
        content: hello world 3
        dest: fichier.txt
      notify: restart apache

    - meta: flush_handlers

    - name: Entraine aussi un changement
      copy:
        content: whatever 3
        dest: whatever.txt
      notify: restart apache

    - debug:
        msg: Fin de playbook

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
