# Playbook du TP3
- name: Playbook TP3
  hosts: all
  become: true
  tasks:

    - name: Make sure the motd is copied
      ansible.builtin.copy:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Make sure the web server is installed on debians
      ansible.builtin.package:
        name: "{{ web_server }}"
        state: present

    - name: Make sure the html file is copied
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

    - name: Make sure the web server is started
      ansible.builtin.service:
        name: "{{ web_server }}"
        state: started
        enabled: true
