# ansible debian1 -i inventory -m setup > debian1.txt

- name: On affiche une variable
  hosts: all
  vars:
    app_deploy_folder: /coucou
  vars_files:
    - my-vars.yml
  tasks:

    - name: This is a block
      when: une_condition
      become: true
      vars:
        # lvl 16
        some_var: some value
      block:
        - name: Task 1
          ansible.builtin.ping:
        - name: Task 2
          ansible.builtin.ping:




    - name: Affichage en mode "var"
      ansible.builtin.debug:
        var: app_deploy_folder

    - ansible.builtin.include_vars:
        file: my-vars.yml #18
    
    - name: Affichage en mode "msg"
      ansible.builtin.debug:
        msg: "{{ app_deploy_folder | default('/path/to/somewhere') }}"
      when: app_deploy_folder is defined
      vars:
        app_deploy_folder: /lvl-17
